---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Debian)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Debian"


- hosts: all
  become: true 
  tasks:
   
  - name: add ssh key for ali
    tags: always
    authorized_key:
      user: ali
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCXnMuJcg0IFhK2WA3PSpY2PlfOkg2I/QiHUD/GAL68jWq4wC55ERFPhiB/FVd4U85z12ABUUrWC/NnAMLSpsiPXaV82z9979ai/mEY5xy+9q9M05ARtrrfqvc3rUsDpHpXn327KWJ6KI8ttiL2Q/c4LRTXChkrCaxiVKZKq+2ccheGDibsYGKvdRlYZFwxccY91SB5ZO5RUdBQ+6Za19nEPs4JtL5uyNNRcuPxxXYmkRk/uGop2J/8YGMGaxcfq94GvO5uR+gERZ3KgQN31pb2tOp/NA1lJNp+oqfyo7cf56vLFCunkUSIy/ZBOq6ss+CA6rRx3NUSaP1/LszljDF9A4RKF6sBXeRQJNtKzgsgiB5PZMkN3JPY2xO6/Vv9Wv3a4pnbj/U+zciIFYQYH+MD38RFUIBqnBR3vMcsfcEWXYR9oZI2yGfCGzUarek3LglocfyTfWaSy4c363t0aY0Cr09hyEyQdZdYOI0hlfJg4H5e2qSYwX+0ynkoax73rB0= ansible"  
  
- hosts: web_servers
  become: true
  tasks:
  
  - name: install apache and php for Debian servers
    tags: apache,apache2,debian
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Debian"

  - name: start apache
    tags: apache2,apache,debian
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_distribution == "Debian"

  - name: copy html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Debian)
    tags: debian,db,mariadb,skp
    apt:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution == "Debian"


- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba,skp
    package:
      name: samba
      state: latest
